# Generated by Django 4.2.2 on 2023-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
