# Generated by Django 4.2.2 on 2024-05-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trace', '0003_whole'),
    ]

    operations = [
        migrations.AddField(
            model_name='whole',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
