# Generated by Django 4.2.2 on 2024-05-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventitems_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wintegrate',
            field=models.BooleanField(default=False),
        ),
    ]
